patchedDependencies:
  groupmq: patches/groupmq.patch
onlyBuiltDependencies:
  - cpu-features
  - esbuild
  - msgpackr-extract
  - protobufjs
  - ssh2
  - unrs-resolver

publicHoistPattern:
  - eslint-plugin-*
  - '@prettier/plugin-*'
